name: Deploy with Serveless Framework on AWS

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    uses: nolram/github-actions/.github/workflows/serverless-cicd.yml@main
    with:
      AWS_REGION: "us-east-1"
      project_type: "node"

    secrets: inherit
