name: Deploy with Serveless Framework on AWS

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  checkout:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

  deploy:
    uses: nolram/github-actions/.github/workflows/serverless-cicd.yml@main
    with:
      AWS_REGION: "us-east-1"
    secrets: inherit
