name: Deploy with Serveless Framework on AWS

on: [push]

permissions:
  contents: read

jobs:
  deploy:
    uses: nolram/github-actions/.github/workflows/check_push_node.yml@main
    secrets: inherit
