name: Check Vulnerabilities in the project

on: [push]

permissions:
  contents: read

jobs:
  push:
    uses: nolram/github-actions/.github/workflows/check_push_node.yml@main
    with:
      project_type: "node"
    secrets: inherit
